### ISSUE TITLE
404 on bundle index when using generic bundle

### ISSUE THREAD

**Issue by domdoescode** [serby/ctrl#69]
To replicate on Unix/Mac:

```
git clone git://github.com/serby/control control-404-error-example
cd control-404-error-example
npm install
git clone git://github.com/domudall/control-404-error-example bundles/vegetable
```

Add `vegetable` to server.js, then start control with `node app`

[Index page](http://localhost:3021/admin/vegetable) returns 404, however all other routes are rendered correctly (going through the process of creation via the [new vegetable page](http://localhost:3021/admin/vegetable/new)).

Tried debugging route defined in [genericAdminRoutes.js](https://github.com/serby/control/blob/master/bundles/generic/lib/genericAdminRoutes.js#L82) but to no avail.

**Comment by serby** [comment]
This is because the article bundle has a catch-all URL that is matching admin/vegetable if you put vegetable before article in server.js it will work.

**Comment by domdoescode** [comment]
Ace, thanks. Updated [Creating a Bundle](https://github.com/serby/control/wiki/Creating-a-Bundle) wiki to reflect this.

Is there a particular reason for the article catch-all?

**Comment by serby** [comment]
It is a functional requirement of the bundle.

So you can do this:

http://clock.co.uk/tech-blogs/upstart-and-nodejs

and manage the section and the article slug from the CMS.

On 31 May 2012 09:49, Dom Udall <
reply@reply.github.com

> wrote:
> 
> Ace, thanks. Updated [Creating a Bundle](https://github.com/serby/control/wiki/Creating-a-Bundle) wiki to reflect
> this.
> 
> Is there a particular reason for the article catch-all?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/serby/control/issues/69#issuecomment-6030779

## 

paul.serby@clock.co.uk
Chief Technology Officer

_Direct: +44 2030 516115__Mobile: +44 7881 550999_
*

## *
- http://www.clock.co.uk/
  *
  *
  *
  The Old School HouseBridge Road, Hunton Bridge,Kings Langley, WD4 8RQ
  Switchboard: +44 1923 261166www.clock.co.uk
  *
  *
- http://twitter.com/clock    https://github.com/clocklimited
  http://www.linkedin.com/company/clock-limited
  http://www.clock.co.uk/blog
  *
  *
  *
  _www.clock.co.uk/email-disclaimer_
  _clock.® is a Registered Trademark of Clock Limited in the European
  Community and other territories_

**Comment by domdoescode** [comment]
Couldn't the admin location be excluded from the catch-all to resolve this? Setting a section with the same URL as the admin section would cause issues as is.

**Comment by serby** [comment]
The problem is that express handles the routing and that makes it hard to
be creative in that layer. In a future version of control I would like to
take express out. making this sort of thing easier.

For now the it is less complicated to manually mange the order the bundles
are included in.

On 31 May 2012 10:08, Dom Udall <
reply@reply.github.com

> wrote:
> 
> Couldn't the admin location be excluded from the catch-all to resolve
> this? Setting a section with the same URL as the admin section would cause
> issues as is.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/serby/control/issues/69#issuecomment-6031110

## 

paul.serby@clock.co.uk
Chief Technology Officer

_Direct: +44 2030 516115__Mobile: +44 7881 550999_
*

## *
- http://www.clock.co.uk/
  *
  *
  *
  The Old School HouseBridge Road, Hunton Bridge,Kings Langley, WD4 8RQ
  Switchboard: +44 1923 261166www.clock.co.uk
  *
  *
- http://twitter.com/clock    https://github.com/clocklimited
  http://www.linkedin.com/company/clock-limited
  http://www.clock.co.uk/blog
  *
  *
  *
  _www.clock.co.uk/email-disclaimer_
  _clock.® is a Registered Trademark of Clock Limited in the European
  Community and other territories_

**Comment by serby** [comment]
More on this here #57
